# Generated by Django 3.1.2 on 2021-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='anon_usr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
