# Generated by Django 3.1.2 on 2021-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210410_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='anon_usr',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
