# Generated by Django 3.1.2 on 2021-04-13 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20210410_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('binfo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=300)),
                ('core_transaction_outlet', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Payment')], max_length=4, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('core_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('pen', 'Pending Order'), ('cmp', 'Completed Order'), ('can', 'Cancelled Order')], default='pen', max_length=10)),
                ('paid_already', models.BooleanField(default=False)),
                ('reference_no', models.CharField(blank=True, max_length=300, null=True)),
                ('billing_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.billinginfo')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.paymenttype')),
                ('products', models.ManyToManyField(blank=True, to='orders.CartObject')),
            ],
        ),
    ]
