# Generated by Django 3.1.2 on 2021-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210413_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='address',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='address_line',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
