# Generated by Django 3.1.2 on 2021-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210413_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='icon',
            field=models.ImageField(null=True, upload_to='payment_method/pics'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='core_transaction_outlet',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Payment'), ('mob', 'Mobile Banking')], max_length=4, null=True),
        ),
    ]
