# Generated by Django 3.1.2 on 2021-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210417_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
