# Generated by Django 3.1.2 on 2021-04-17 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail_instruction', models.TextField(blank=True)),
                ('account_name', models.CharField(blank=True, max_length=800)),
                ('account_no', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.paymentdetail'),
        ),
    ]
